service: fastapi-lambda

provider:
  name: aws
  runtime: python3.11
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  environment:
    STAGE: ${self:provider.stage}
  logRetentionInDays: 30
  
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: '*'

functions:
  api:
    handler: src.main.handler
    name: ${self:service}-${self:provider.stage}
    memorySize: 256
    timeout: 30
    layers:
      - !Ref DependenciesLambdaLayer
    events:
      - httpApi:
          path: /{proxy+}
          method: '*'
    environment:
      # Add your function-specific env vars here
      API_ENV: ${self:provider.stage}

layers:
  dependencies:
    name: ${self:service}-layer-${self:provider.stage}
    description: Python dependencies for FastAPI
    compatibleRuntimes:
      - python3.11
    path: layer

package:
  patterns:
    - 'src/**'             # Include all files in src directory
    - '!src/**/*.pyc'      # Exclude compiled Python files
    - '!src/__pycache__/**'
    - '!src/**/.pytest_cache/**'
    - '!src/**/.coverage'
    - '!src/**/tests/**'
    - '!node_modules/**'
    - '!venv/**'
    - '!.venv/**' 