name: Deploy to Amplify

on:
  push:
    branches: [ main, amplify_deployment ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      APP_NAME: "fastapi-lambda-app"
    
    steps:
      - uses: actions/checkout@v3
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Amplify CLI
        run: |
          npm install -g @aws-amplify/cli
          amplify --version
        
      - name: Configure Amplify
        run: |
          # Try to get app ID by name
          APP_ID=$(aws amplify list-apps --query "apps[?name=='${APP_NAME}'].appId" --output text)
          
          if [ -z "$APP_ID" ]; then
            echo "Creating new Amplify app..."
            APP_ID=$(aws amplify create-app --name "${APP_NAME}" --platform "WEB" --query 'app.appId' --output text)
          else
            echo "Found existing Amplify app with ID: ${APP_ID}"
          fi
          
          # Export APP_ID for subsequent steps
          echo "APP_ID=${APP_ID}" >> $GITHUB_ENV
          
          # Create deployment bucket if it doesn't exist
          DEPLOYMENT_BUCKET="amplify-${APP_NAME}-${APP_ID}-deployment"
          if ! aws s3api head-bucket --bucket "$DEPLOYMENT_BUCKET" 2>/dev/null; then
            if [ "$AWS_REGION" = "us-east-1" ]; then
              aws s3api create-bucket \
                --bucket "$DEPLOYMENT_BUCKET" \
                --region "$AWS_REGION"
            else
              aws s3api create-bucket \
                --bucket "$DEPLOYMENT_BUCKET" \
                --region "$AWS_REGION" \
                --create-bucket-configuration LocationConstraint="$AWS_REGION"
            fi
          fi
          
          # Export deployment bucket name
          echo "DEPLOYMENT_BUCKET=${DEPLOYMENT_BUCKET}" >> $GITHUB_ENV
          
          # Initialize Amplify project with API Gateway configuration
          amplify init \
            --appId ${APP_ID} \
            --envName prod \
            --yes \
            --categories '{"api":{"deploymentBucket":"'${DEPLOYMENT_BUCKET}'","apiType":"REST"}}'
          
          # Add API with API Gateway integration
          amplify add api \
            --service Lambda \
            --name fastapi \
            --runtime python3.11 \
            --template "REST API with Lambda Integration" \
            --paths "/,/items,/items/{item_id}" \
            --methods "GET,GET,POST" \
            --yes

      - name: Build and Package
        run: |
          # Install dependencies
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --without dev
          
          # Create deployment package
          mkdir -p amplify/backend/api/fastapi/src
          cp -r src/* amplify/backend/api/fastapi/src/
          cp pyproject.toml poetry.lock amplify/backend/api/fastapi/
          
          # Create and upload function zip
          cd amplify/backend/api/fastapi
          zip -r function.zip ./*
          aws s3 cp function.zip s3://${DEPLOYMENT_BUCKET}/amplify-builds/fastapi-prod-latest.zip
          cd ../../../../

      - name: Deploy with Amplify
        run: |
          amplify push \
            --yes \
            --allow-destructive-updates
        env:
          CI: true
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          
      - name: Get API URL
        run: |
          # Get and display the API endpoint URL
          API_ID=$(aws amplify get-backend-environment \
            --app-id ${APP_ID} \
            --environment-name prod \
            --query 'backendEnvironment.apiId' \
            --output text)
          
          API_URL="https://${API_ID}.execute-api.${AWS_REGION}.amazonaws.com/prod"
          echo "API_URL=${API_URL}" >> $GITHUB_ENV
          echo "API is available at: ${API_URL}" 