name: Deploy to Amplify

on:
  push:
    branches: [ main, amplify_deployment ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      APP_NAME: "fastapi-lambda-app"
    
    steps:
      - uses: actions/checkout@v3
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Amplify CLI
        run: |
          npm install -g @aws-amplify/cli
          amplify --version
        
      - name: Configure Amplify
        run: |
          # Try to get app ID by name
          APP_ID=$(aws amplify list-apps --query "apps[?name=='${APP_NAME}'].appId" --output text)
          
          if [ -z "$APP_ID" ]; then
            echo "Creating new Amplify app..."
            APP_ID=$(aws amplify create-app --name "${APP_NAME}" --platform "WEB" --query 'app.appId' --output text)
          else
            echo "Found existing Amplify app with ID: ${APP_ID}"
          fi
          
          # Export APP_ID for subsequent steps
          echo "APP_ID=${APP_ID}" >> $GITHUB_ENV
          
          # Initialize Amplify project
          amplify init \
            --appId ${APP_ID} \
            --envName prod \
            --yes
          
          # Add API if it doesn't exist
          if ! amplify api get; then
            amplify add api \
              --service Lambda \
              --name fastapi \
              --runtime python3.11 \
              --template "Hello World" \
              --yes
          fi

      - name: Create S3 Bucket and Build
        run: |
          # Get deployment bucket from Amplify backend
          DEPLOYMENT_BUCKET=$(aws amplify get-backend-environment \
            --app-id ${{ env.APP_ID }} \
            --environment-name prod \
            --query 'backendEnvironment.deploymentArtifacts' \
            --output text)
          
          # Install dependencies
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --without dev
          
          # Create deployment package
          mkdir -p amplify/backend/api/fastapi/src
          cp -r src/* amplify/backend/api/fastapi/src/
          cp pyproject.toml poetry.lock amplify/backend/api/fastapi/
          
          # Create and upload function zip
          cd amplify/backend/api/fastapi
          zip -r function.zip ./*
          aws s3 cp function.zip s3://${DEPLOYMENT_BUCKET}/amplify-builds/fastapi-prod-latest.zip
          cd ../../../../

      - name: Deploy with Amplify
        run: |
          amplify push \
            --yes \
            --allow-destructive-updates
        env:
          CI: true
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }} 