name: Deploy to Amplify

on:
  push:
    branches: [ main, amplify_deployment ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Amplify CLI
        run: |
          npm install -g @aws-amplify/cli
          amplify --version
        
      - name: Configure Amplify
        run: |
          # Check if app exists
          if ! aws amplify get-app --app-id de7wiwdtok231 2>/dev/null; then
            # Create new app if it doesn't exist
            aws amplify create-app --name "fastapi-lambda-app" --platform "WEB"
          fi
          
          # Initialize Amplify project
          amplify init \
            --appId de7wiwdtok231 \
            --envName prod \
            --yes
          
          # Add API if it doesn't exist
          if ! amplify api get; then
            amplify add api \
              --service Lambda \
              --name fastapi \
              --runtime python3.11 \
              --template "Hello World" \
              --yes
          fi

      - name: Create S3 Bucket and Build
        run: |
          # Create S3 bucket if it doesn't exist
          BUCKET_NAME="amplify-fastapi-lambda-${AWS_REGION}"
          if ! aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
            aws s3api create-bucket \
              --bucket "$BUCKET_NAME" \
              --region "$AWS_REGION" \
              --create-bucket-configuration LocationConstraint="$AWS_REGION"
          fi
          
          # Install dependencies
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --without dev
          
          # Create deployment package
          mkdir -p amplify/backend/api/fastapi/src
          cp -r src/* amplify/backend/api/fastapi/src/
          cp pyproject.toml poetry.lock amplify/backend/api/fastapi/
          
          # Create and upload function zip
          cd amplify/backend/api/fastapi
          zip -r function.zip ./*
          aws s3 cp function.zip s3://${BUCKET_NAME}/amplify-builds/fastapi-prod-latest.zip
          cd ../../../../

      - name: Deploy with Amplify
        run: |
          amplify push \
            --yes \
            --allow-destructive-updates
        env:
          CI: true
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }} 